# ---- Global Settings --------------------------------------------------
# Listen on VLAN subinterfaces only - never on the WAN port (eth0)
interface=eth1.10
interface=eth1.20
bind-interfaces

#Upstream DNS: external queries forwarded to Cloudflare and Google
server=1.1.1.1
server=8.8.8.8


#Cache 1000 DNS entries for faster repeat lookups
cache-size=1000

#Block DNS rebinding attacks
stop-dns-rebind
rebind-localhost-ok


# ----------- VLAN 10 (eth1.10) ---------------------
#Assign IPs 192.168.10.100-200, 24-hour lease
dhcp-range=eth1.10,192.168.10.100,192.168.10.200,255.255.255.0,24h

# Tell devices the Pi is their gateway
dhcp-option=eth1.10,option:router,192.168.10.1

# Tell devices the Pi handles their DNS
dhcp-option=eth1.10,option:dns-server,192.168.10.1


# --------- VLAN 20 (eth1.20) -------------------
# Assign IPs 192.168.20.100-200, 24-hour lease
dhcp-range=eth1.20,192.168.20.100,192.168.20.200,255.255.255.0,24h

# Tell IoT devices the pi is their gateway
dhcp-option=eth1.20,option:router,192.168.20.1

# Tell IoT devices the Pi handles their DNS
dhcp-option=eth1.20,option:dns-server,192.168.20.1


# ---- Logging ---------------------------------------
log-dhcp



