#!/usr/sbin/nft -f

# Remove all existing rules before loading fresh ones
flush ruleset

# --------------------------------------------
# FILTER TABLE
# --------------------------------------------
table inet filter {

	# --- INPUT: traffic destined for the Pi -----------
	chain input {
		type filter hook input priority 0; policy drop;

		# Always allow loopback
		iif "lo" accept

		# Allow replies to already-established connections
		ct state established,related accept

		# Drop malformed packets
		ct state invalid drop

		# Allow SSH from VLAN 10  only
		# IoT devices on VLAN 20 cannot SSH into the router
		iif "eth1.10" tcp dport 22 accept


		# Allow SSH from home via eth0
		# Remove this rule  after testing
		iif "eth0" ip saddr 192.168.40.0/24 tcp dport 22 accept

		# Allow DHCP from both VLANs
		# (Clients broadcast to port 67 when joining the network)
		iif "eth1.10" udp dport 67 accept
		iif "eth1.20" udp dport 67 accept

		# Allow DNS queries from both VLANs
		iif "eth1.10" udp dport 53 accept
		iif "eth1.10" tcp dport 53 accept
		iif "eth1.20" udp dport 53 accept
		iif "eth1.20" tcp dport 53 accept

		# Allow ping to the Pi from both VLANs (for Diagnostics)
		iif "eth1.10" icmp type echo-request accept
		iif "eth1.20" icmp type echo-request accept

		# Allow ping to Pi from Home network
		iif "eth0" icmp type echo-request accept
	}


	# -- FORWARD: Traffic PASSING THROUGH the Pi ------------------
	chain forward	{
		type filter hook forward priority 0; policy drop;

		# Allow replies to established connections
		ct state established,related accept

		# Drop malformed packets
		ct state invalid drop

		# ---  INTERNET ACCESS ----------------------------
		# Personal devices can reach the internet
		iif "eth1.10" oif "eth0" accept

		# IoT devices can reach the internet
		iif "eth1.20" oif "eth0" accept

		# --- VLAN ISOLATION ------------------------------
		# ALLOWED: personal devices CAN reach IoT devices
		iif "eth1.10" oif "eth1.20" accept

		# BLOCKED: IoT devices  CANNOT reach personal devices
		# This is the  critical security rule.
		# A compromised IoT device cannot attack your laptop or NAS.
		iif "eth1.20" oif "eth1.10" drop
	}

	# ------- OUTPUT: traffic generated by the Pi ---------------------
	chain output {
		type filter hook output priority 0; policy accept;
 	}
}

# ------------------------------------------
# NAT TABLE
# -----------------------------------------
table inet nat {
	chain postrouting {
		type nat hook postrouting priority 100;

		# When traffic leaves via  eth0 (internet), rewrite
		# the source IP to the Pi's public IP.
		# Applies to both VLAN 10 and VLAN 20 traffic.
		oif "eth0" masquerade
	}
}
